const TEAM_FIREBASE_CONFIG={apiKey:"AIzaSyCzB4_YotWCPVh1yaqWkhbB4LypPQYvV4U",authDomain:"site-lamed.firebaseapp.com",projectId:"site-lamed",storageBucket:"site-lamed.firebasestorage.app",messagingSenderId:"862756160215",appId:"1:862756160215:web:d0fded233682bf93eaa692"};
const TEAM_ADMIN_UIDS=new Set(["NoGsCqiKc0VJwWb6rppk7QVLV1B2"]);let teamAuth;let teamMembers=[];let passwordTarget=null;
const team$=selector=>document.querySelector(selector);
const teamEscape=value=>String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");
function setTeamFeedback(message,type=""){const node=team$("#team-feedback");node.textContent=message||"";node.className=`team-feedback ${type}`.trim()}
async function isTeamAdmin(user){if(!user)return false;if(TEAM_ADMIN_UIDS.has(user.uid))return true;try{return(await user.getIdTokenResult()).claims?.admin===true}catch{return false}}
async function teamApi(action,payload={}){const token=await teamAuth.currentUser.getIdToken();const response=await fetch(`/api/admin/team/${action}`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.error||"Não foi possível concluir a operação.");return data}
function renderTeam(){team$("#team-total").textContent=teamMembers.length;const list=team$("#team-list");if(!teamMembers.length){list.innerHTML='<p class="empty-state">Nenhuma conta de produção cadastrada.</p>';return}list.innerHTML=teamMembers.map(member=>`<article class="member-row" data-member="${teamEscape(member.uid)}"><div class="member-main"><div class="member-avatar">${teamEscape((member.name||"?").charAt(0).toUpperCase())}</div><div><strong>${teamEscape(member.name)} <span class="status-badge ${member.disabled?'disabled':''}">${member.disabled?'Bloqueado':'Ativo'}</span></strong><span>Usuário: ${teamEscape(member.username)}</span></div></div><div class="member-actions"><select class="member-role" data-role="${teamEscape(member.uid)}" aria-label="Permissão de ${teamEscape(member.name)}"><option value="production" ${member.role==='production'?'selected':''}>Somente produção</option><option value="admin" ${member.role==='admin'?'selected':''}>Administrador completo</option></select><button class="member-action" data-password="${teamEscape(member.uid)}"><i class="fa-solid fa-key"></i> Senha</button><button class="member-action ${member.disabled?'':'danger'}" data-status="${teamEscape(member.uid)}" data-disabled="${member.disabled?'false':'true'}"><i class="fa-solid ${member.disabled?'fa-lock-open':'fa-ban'}"></i> ${member.disabled?'Reativar':'Bloquear'}</button></div></article>`).join("")}
async function loadTeam(){try{setTeamFeedback("Carregando equipe…");const data=await teamApi("list");teamMembers=data.members||[];renderTeam();setTeamFeedback("")}catch(error){setTeamFeedback(error.message,"error")}}
function normalizeTeamUsername(value){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\s+/g,".").replace(/[^a-z0-9._-]/g,"").replace(/^[._-]+|[._-]+$/g,"")}
async function createMember(event){event.preventDefault();const button=event.submitter;button.disabled=true;try{const data=await teamApi("create",{name:team$("#team-name").value.trim(),username:normalizeTeamUsername(team$("#team-username").value),password:team$("#team-password").value,role:team$("#team-role").value});teamMembers=data.members||[];renderTeam();event.target.reset();setTeamFeedback("Acesso criado. Entregue o usuário e a senha temporária à pessoa.","success")}catch(error){setTeamFeedback(error.message,"error")}finally{button.disabled=false}}
async function handleTeamClick(event){const passwordButton=event.target.closest("[data-password]");if(passwordButton){passwordTarget=teamMembers.find(item=>item.uid===passwordButton.dataset.password);team$("#password-person").textContent=`Conta de ${passwordTarget?.name||"produção"}`;team$("#new-team-password").value="";team$("#password-dialog").showModal();return}const statusButton=event.target.closest("[data-status]");if(statusButton){statusButton.disabled=true;try{const data=await teamApi("status",{uid:statusButton.dataset.status,disabled:statusButton.dataset.disabled==="true"});teamMembers=data.members||[];renderTeam();setTeamFeedback("Status da conta atualizado.","success")}catch(error){setTeamFeedback(error.message,"error")}finally{statusButton.disabled=false}}}
async function handleRole(event){const select=event.target.closest("[data-role]");if(!select)return;select.disabled=true;try{const data=await teamApi("role",{uid:select.dataset.role,role:select.value});teamMembers=data.members||[];renderTeam();setTeamFeedback("Permissão atualizada. A pessoa deverá entrar novamente.","success")}catch(error){setTeamFeedback(error.message,"error");await loadTeam()}finally{select.disabled=false}}
async function savePassword(event){event.preventDefault();if(!passwordTarget)return;const button=event.submitter;button.disabled=true;try{await teamApi("password",{uid:passwordTarget.uid,password:team$("#new-team-password").value});team$("#password-dialog").close();setTeamFeedback(`Nova senha salva para ${passwordTarget.name}.`,"success")}catch(error){setTeamFeedback(error.message,"error")}finally{button.disabled=false}}
function bindTeam(){team$("#team-create-form").addEventListener("submit",createMember);team$("#team-refresh").addEventListener("click",loadTeam);team$("#team-list").addEventListener("click",handleTeamClick);team$("#team-list").addEventListener("change",handleRole);team$("#password-form").addEventListener("submit",savePassword);team$("#password-close").addEventListener("click",()=>team$("#password-dialog").close());document.querySelectorAll("[data-toggle-password]").forEach(button=>button.addEventListener("click",()=>{const input=team$(`#${button.dataset.togglePassword}`);input.type=input.type==="password"?"text":"password";button.innerHTML=`<i class="fa-regular ${input.type==="password"?'fa-eye':'fa-eye-slash'}"></i>`}));team$("#team-username").addEventListener("blur",event=>{event.target.value=normalizeTeamUsername(event.target.value)})}
function initTeam(){if(!firebase.apps.length)firebase.initializeApp(TEAM_FIREBASE_CONFIG);teamAuth=firebase.auth();bindTeam();teamAuth.onAuthStateChanged(async user=>{if(!await isTeamAdmin(user)){location.replace("login-admin.html");return}document.body.classList.remove("team-auth-pending");loadTeam()})}
window.addEventListener("DOMContentLoaded",initTeam);
